/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      flex: {
        2: '2',
        3: '3',
        4: '4',
      },
      fontFamily: {
        normal: ['SofiaPro-Regular'],
        medium: ['SofiaPro-Medium'],
        semibold: ['SofiaPro-SemiBold'],
        bold: ['SofiaPro-Bold'],
      },
      colors: {
        'primary-main': '#0A6E9E',
        'primary-80': '#2980A8',
        'primary-50': '#5BA3C2',
        'primary-20': '#A3D0E4',
        'secondary-main': '#F16A00',
        'secondary-80': '#f48f3a',
        'secondary-50': '#f7b87a',
        'secondary-20': '#fbe3cc',
        'tertiary-main': '#FEAC00',
        'tertiary-80': '#feb82e',
        'tertiary-50': '#fed46e',
        'tertiary-20': '#fff2cc',
        'quaternary-main': '#C1A000',
        'quaternary-80': '#d1b833',
        'quaternary-50': '#e2cf66',
        'quaternary-20': '#f3e799',
        'error-main': '#F30000',
        'error-80': '#F34C4C',
        'error-50': '#F38585',
        'error-20': '#F3BEBE',
        'gray-main': '#9A9FAE',
        'gray-80': '#A8ACB9',
        'gray-50': '#C4C7D0',
        'gray-20': '#EBEBEB',
        title: '#2196F3',
        subtitle: '#cdd7f8',
      },
    },
  },
  plugins: [],
};
